version: '3.9'

services:
  redis:
    image: redis/redis-stack-server:7.0.0-RC5
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli -p 6379 ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=ycsb
